title: "Junteng Liu"
title_separator: "-"
name: "Junteng Liu"
description: "PhD Candidate at HKUST NLP Group | Research in Natural Language Processing & Machine Learning"
url: "https://wubart.github.io"
baseurl: "/LJT-Homepage"
repository: "wubart/LJT-Homepage"

author:
  name: "Junteng Liu"
  avatar: "/assets/images/avatar.jpg"
  email: "jliugi@connect.ust.hk"
  bio: "First-year PhD candidate at the HKUST NLP Group, focusing on natural language processing and machine learning, with research interests in LLM reasoning, VLM hallucination, and LLM truthfulness."
  location: "Hong Kong"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/junteng88716710"